name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  create_version_of_code:
    name: My verson
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./versionig/requirements.txt

      - name: execute py script # run main.py
        run: export verion_app={{python ./versionig/versionig.py}}

      outputs:
        version_app: ${{ steps.m }}



  auth_server_push_to_registry:
    name: Push Auth Server Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: create_version_of_code
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ifilyaninitmo/auth-server-mega-itmo
      
      - name: Build and push Docker image Auth Server
        uses: docker/build-push-action@v2
        with:
          context: ./auth_server/
          push: true
          tags: ${{ needs.create_version_of_code.outputs.version_app }}
          labels: ${{ steps.meta.outputs.labels }}

  time_server_push_to_registry:
    name: Push Time Server Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ifilyaninitmo/time-server-mega-itmo
      
      - name: Build and push Docker image Auth Server
        uses: docker/build-push-action@v2
        with:
          context: ./time_server/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}