name: Linter Python code 

on:
  push:
    branches:
      - main
jobs:
  linter-python:
    name: Linter 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "code/time_server"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          isort-options: "-w 100"